services:
  - type: web
    name: babybliss-client
    env: static
    buildCommand: yarn && yarn build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: "/(.*)"
        destination: "/index.html"
