services:
  - type: web
    name: babybliss-server
    env: node
    plan: free
    branch: main
    region: oregon
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://anuruddhlu7234_db_user:QEemrq15d8CuhYCZ@cluster0.jfcxyd0.mongodb.net/babybliss?retryWrites=true&w=majority"
      - key: JWT_SECRET
        value: supersecretkey123
      - key: PORT
        value: 5000

  - type: static_site
    name: babybliss-client
    branch: main
    buildCommand:  npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://assbabes.onrender.com/api
      - key: REACT_APP_API_URL
        value: https://assbabes.onrender.com/api